import "./styles.css";
import "./category-editor.css";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { api,isTauri } from "./api";
import type { Category,Clip,ClipQuery,ContentType,Grouping,Settings } from "./types";
import { hydrateIcons } from "./ui/icons";
import { mainWindowShell } from "./ui/main-window";
import { popupShell } from "./ui/popup";
import { relativeTime } from "./ui/time";

const popup=new URLSearchParams(location.search).get("mode")==="popup";
const state:{clips:Clip[];categories:Category[];settings:Settings|null;search:string;type:ContentType|null;category:string|null;domain:string|null;grouping:Grouping;selected:number;hasMore:boolean}={clips:[],categories:[],settings:null,search:"",type:null,category:null,domain:null,grouping:"none",selected:0,hasMore:false};
const app=document.querySelector<HTMLElement>("#app")!;
const esc=(value:string)=>value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]!));
const tag=(text:string,className="",style="")=>`<span class="tag ${className}" ${style}>${esc(text)}</span>`;
function query():ClipQuery{return{search:state.search||undefined,contentType:state.type||undefined,categoryId:state.category||undefined,domain:state.domain||undefined,limit:popup?16:60};}
async function refresh(){state.clips=await api.list(query());state.hasMore=!popup&&state.clips.length===60;state.selected=Math.min(state.selected,Math.max(0,state.clips.length-1));renderCards();}
function filters(){const types:ContentType[]=["Text","Links","Email","Numbers"];const domains=[...new Set(state.clips.map(c=>c.domain).filter((v):v is string=>!!v))].slice(0,5);return `<div class="filter-rail" role="toolbar" aria-label="Фильтры"><button class="filter ${!state.type&&!state.category&&!state.domain?"active":""}" data-filter="all">Все</button>${types.map(t=>`<button class="filter type-${t.toLowerCase()} ${state.type===t?"active":""}" data-type="${t}">${t}</button>`).join("")}${state.categories.map(c=>`<button class="filter user-filter ${state.category===c.id?"active":""}" data-category="${c.id}" style="--tag:${c.color}">${esc(c.name)}</button>`).join("")}${domains.map(d=>`<button class="filter domain-filter ${state.domain===d?"active":""}" data-domain="${esc(d)}">${esc(d)}</button>`).join("")}${popup?"":`<button class="filter add-category" data-action="new-category"><i data-lucide="plus"></i> Категория</button>`}</div>`;}
function shell(){app.className=popup?"popup-shell":"main-shell";const filterMarkup=filters();app.innerHTML=popup?popupShell(filterMarkup):mainWindowShell(filterMarkup);bindShell();renderCards();hydrateIcons(app);}
function clipCard(c:Clip,index:number){const categories=c.categories.map(x=>`<button class="tag user-tag" style="--tag:${x.color}" data-unassign="${x.id}" title="Убрать категорию">${esc(x.name)}${popup?"":" ×"}</button>`).join("");return `<article class="clip-card type-edge-${c.contentType.toLowerCase()} ${popup&&index===state.selected?"selected":""}" tabindex="0" data-clip="${c.id}" draggable="${!popup}" aria-label="Скопировать фрагмент"><div class="card-meta">${tag(c.contentType,`type-${c.contentType.toLowerCase()}`)}${c.domain?tag(c.domain,"domain-tag"):""}${categories}<time>${relativeTime(c.lastCopiedAt)}</time></div><p class="preview">${esc(c.content)}</p>${c.pageTitle?`<p class="page-title">${esc(c.pageTitle)}</p>`:""}<div class="card-foot"><span>${c.copyCount>1?`скопировано ${c.copyCount} раза`:"одна копия"}</span>${popup?"":`<div class="card-actions"><button data-action="pin" aria-label="${c.pinned?"Открепить":"Закрепить"}"><i data-lucide="${c.pinned?"pin-off":"pin"}"></i></button><button data-action="delete" aria-label="Удалить"><i data-lucide="trash-2"></i></button></div>`}${c.pinned?`<i class="pin-corner" data-lucide="pin"></i>`:""}</div></article>`;}
function groups():[string,Clip[]][] {if(state.grouping==="none")return[["",state.clips]];if(state.grouping==="type")return(["Text","Links","Email","Numbers"]as ContentType[]).map(t=>[t,state.clips.filter(c=>c.contentType===t)]);if(state.grouping==="domain")return[["youtube.com",state.clips.filter(c=>c.domain==="youtube.com")],["github.com",state.clips.filter(c=>c.domain==="github.com")],["Другие домены",state.clips.filter(c=>c.domain&&c.domain!=="youtube.com"&&c.domain!=="github.com")],["Без источника",state.clips.filter(c=>!c.domain)]];return[...state.categories.map(cat=>[cat.name,state.clips.filter(c=>c.categories.some(x=>x.id===cat.id))]as[string,Clip[]]),["Без категории",state.clips.filter(c=>!c.categories.length)]];}
function renderCards(){const root=document.querySelector<HTMLElement>("#cards");if(!root)return;if(!state.clips.length){root.innerHTML=`<div class="empty"><div class="empty-paper"><i data-lucide="clipboard"></i></div><h3>${state.search?"Ничего не найдено":"История пока пуста"}</h3><p>${state.search?"Попробуйте другой запрос или сбросьте фильтры.":"Скопируйте текст через Ctrl+C — он появится здесь."}</p></div>`;hydrateIcons(root);return;}if(popup){root.innerHTML=state.clips.map(clipCard).join("");}else{root.innerHTML=groups().filter(([,clips])=>clips.length).map(([name,clips])=>`<section class="clip-group"><h3>${esc(name)}</h3><div class="clip-grid">${clips.map((c,i)=>clipCard(c,i)).join("")}</div></section>`).join("")+`${state.hasMore?'<button class="load-more" data-load-more>Показать ещё</button>':""}`;}bindCards(root);root.querySelector("[data-load-more]")?.addEventListener("click",loadMore);hydrateIcons(root);}
async function loadMore(){const next=await api.list({...query(),offset:state.clips.length});state.clips.push(...next);state.hasMore=next.length===60;renderCards();}
function bindShell(){const input=document.querySelector<HTMLInputElement>("#search")!;let timer=0;input.addEventListener("input",()=>{state.search=input.value;clearTimeout(timer);timer=window.setTimeout(refresh,120)});if(popup)setTimeout(()=>input.focus(),20);document.querySelector("#grouping")?.addEventListener("change",e=>{state.grouping=(e.target as HTMLSelectElement).value as Grouping;renderCards()});document.querySelectorAll<HTMLElement>("[data-type]").forEach(el=>el.onclick=()=>{state.type=state.type===el.dataset.type?null:el.dataset.type as ContentType;state.category=state.domain=null;shell();refresh()});document.querySelectorAll<HTMLElement>("[data-category]").forEach(el=>{el.onclick=()=>{state.category=state.category===el.dataset.category?null:el.dataset.category!;state.type=state.domain=null;shell();refresh()};el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const id=e.dataTransfer?.getData("text/pastily");if(id)api.assign(id,el.dataset.category!).then(reload)}});document.querySelectorAll<HTMLElement>("[data-domain]").forEach(el=>el.onclick=()=>{state.domain=state.domain===el.dataset.domain?null:el.dataset.domain!;state.type=state.category=null;shell();refresh()});document.querySelector<HTMLElement>("[data-filter=all]")!.onclick=()=>{state.type=state.category=state.domain=null;shell();refresh()};document.querySelector("[data-action=new-category]")?.addEventListener("click",showCategoryModal);document.querySelector("[data-action=settings]")?.addEventListener("click",showSettings);}
function bindCards(root:HTMLElement){root.querySelectorAll<HTMLElement>("[data-clip]").forEach(card=>{const clip=state.clips.find(c=>c.id===card.dataset.clip)!;card.onclick=e=>{if((e.target as HTMLElement).closest("button"))return;api.copy(clip,popup)};card.onkeydown=e=>{if(e.key==="Enter")api.copy(clip,popup)};card.ondragstart=e=>e.dataTransfer?.setData("text/pastily",clip.id);card.querySelector<HTMLElement>("[data-action=pin]")?.addEventListener("click",()=>api.pin(clip.id,!clip.pinned).then(reload));card.querySelector<HTMLElement>("[data-action=delete]")?.addEventListener("click",()=>api.remove(clip.id).then(reload));card.querySelectorAll<HTMLElement>("[data-unassign]").forEach(x=>x.onclick=()=>api.unassign(clip.id,x.dataset.unassign!).then(reload));});}
function modal(title:string,body:string){const root=document.querySelector<HTMLElement>("#modal-root")!;root.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><header><h2>${title}</h2><button data-close aria-label="Закрыть"><i data-lucide="x"></i></button></header>${body}</section></div>`;root.querySelector("[data-close]")?.addEventListener("click",()=>root.innerHTML="");hydrateIcons(root);return root;}
function showCategoryModal(){const existing=state.categories.map(c=>`<form class="category-edit" data-edit="${c.id}"><input name="name" maxlength="60" required value="${esc(c.name)}"/><input name="color" type="color" value="${c.color}"/><button type="submit">Сохранить</button><button type="button" data-delete="${c.id}"><i data-lucide="trash-2"></i></button></form>`).join("");const root=modal("Категории",`<div class="category-list">${existing||"<p class=notice>Пользовательских категорий пока нет.</p>"}</div><form id="category-form"><label>Новая категория<input name="name" maxlength="60" required placeholder="Например, Japanese"/></label><label>Цвет<input name="color" type="color" value="#f2a65a"/></label><button class="primary" type="submit">Создать категорию</button></form>`);root.querySelector<HTMLFormElement>("#category-form")!.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target as HTMLFormElement);await api.createCategory(String(fd.get("name")),String(fd.get("color")));root.innerHTML="";await reload()});root.querySelectorAll<HTMLFormElement>("[data-edit]").forEach(form=>form.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(form);await api.updateCategory(form.dataset.edit!,String(fd.get("name")),String(fd.get("color")));root.innerHTML="";await reload()}));root.querySelectorAll<HTMLElement>("[data-delete]").forEach(button=>button.onclick=async()=>{await api.deleteCategory(button.dataset.delete!);root.innerHTML="";await reload()});}
function showSettings(){const s=state.settings!;const root=modal("Настройки",`<form id="settings-form"><label class="switch-row"><span><b>Запись истории</b><small>Отслеживать обычный X11 Clipboard</small></span><input name="recording" type="checkbox" ${s.paused?"":"checked"}/></label><label class="switch-row"><span><b>Автозапуск</b><small>Запускать после входа в KDE</small></span><input name="autostart" type="checkbox" ${s.autostart?"checked":""}/></label><label>Горячая клавиша<input name="shortcut" value="${esc(s.shortcut)}"/></label><label>Хранить незакреплённые карточки, дней<input name="retention" type="number" min="1" max="3650" value="${s.retentionDays}"/></label><div class="notice">Исключение приложений подготовлено архитектурно, но отключено в MVP: X11 не сообщает надёжно источник Clipboard во всех случаях.</div><button class="primary" type="submit">Сохранить</button><button class="danger" type="button" data-clear>Очистить незакреплённую историю</button></form>`);root.querySelector("[data-clear]")?.addEventListener("click",()=>api.clear().then(reload));root.querySelector("form")!.addEventListener("submit",async e=>{e.preventDefault();const fd=new FormData(e.target as HTMLFormElement);const next={...s,paused:fd.get("recording")!=="on",autostart:fd.get("autostart")==="on",shortcut:String(fd.get("shortcut")),retentionDays:Number(fd.get("retention"))};await api.saveSettings(next);state.settings=next;root.innerHTML="";});}
async function reload(){const data=await api.bootstrap(popup);state.clips=data.clips;state.categories=data.categories;state.settings=data.settings;state.hasMore=!popup&&data.clips.length===60;shell();}
document.addEventListener("keydown",e=>{if(!popup)return;if(e.key==="Escape"){if(isTauri)getCurrentWindow().hide();}else if(e.key==="ArrowDown"){e.preventDefault();state.selected=Math.min(state.selected+1,state.clips.length-1);renderCards();}else if(e.key==="ArrowUp"){e.preventDefault();state.selected=Math.max(0,state.selected-1);renderCards();}else if(e.key==="Enter"&&document.activeElement?.id==="search"&&state.clips[state.selected])api.copy(state.clips[state.selected]!,true)});
if(popup&&isTauri)getCurrentWindow().onFocusChanged(({payload})=>{if(!payload)getCurrentWindow().hide();else document.querySelector<HTMLInputElement>("#search")?.focus()});
reload();if(isTauri){listen("clips-changed",reload);listen("open-settings",showSettings);}
